apiVersion: v1
kind: Service
metadata:
  name: {{ include "emailservice.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "emailservice.name" . }}
  ports:
  - name: grpc
    port: 5050
    targetPort: 8080